name: Track Traffic for All Public Repos

on:
  schedule:
    - cron: "0 0 * * *"     # runs daily at 00:00 UTC
  workflow_dispatch:         # allow manual trigger

jobs:
  collect-traffic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tracker repo
        uses: actions/checkout@v4

      - name: Prepare data directory
        run: mkdir -p data

      - name: Fetch traffic for all repos
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TRAFFIC_TOKEN }}
        run: |
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Fetching traffic at $DATE"

          while IFS= read -r REPO; do
            [ -z "$REPO" ] && continue
            echo "➡️  $REPO"

            mkdir -p "data/$REPO"
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$REPO/traffic/views" > "data/$REPO/views.json"
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$REPO/traffic/clones" > "data/$REPO/clones.json"

            # wrap together with timestamp
            echo "{ \"repo\": \"$REPO\", \"date\": \"$DATE\", \"views\": $(cat data/$REPO/views.json), \"clones\": $(cat data/$REPO/clones.json) }" \
              > "data/$REPO/traffic-$DATE.json"
          done < repos.txt

      - name: Commit updated stats
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "Traffic update $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
